# 20 minutes of pandas
This workbook starts with the copy of the code of "10 minutes of pandas"
The most complete jupyter HELP file on pandas of mine.
There is more or less a logic line but not always.
The jupyter notebook tries to put together the most important things but as starter.
It does not go deep of kind of complicated queries since I dont think I need that.

In [2]:
# importing the neccesary libraries.

# importing numpy for arrays.
# note: since pandas is built on top of numpy I think that if pandas is imported 
# there is no need to import numpy. 
import numpy as np

# pandas dataframe library:
import pandas as pd

# in order to visualize data matplotlib
import matplotlib.pyplot as plt
# the follwoing is a special nomenclature for using matplotlib within a jupyter notebook
%matplotlib inline

# in order to generated ramdomly generated numpy arrays
import random

## Creating a NUMPY array

In [3]:
# create a one dimensional array with numpy with values from 1 to 21 with step 1
onp=np.arange(1,21,1)
print('onp numpy array is:')
print(onp)
onp=onp.reshape(4,5)
# notice how the dimensions have to fit. 4x5=20 which is the number of elements.
print('onp numpy array reshaped is:')
print(onp)

onp numpy array is:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
onp numpy array reshaped is:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Creating a series with pandas
my explanation:
A series can be seen as a one dimensional pandas dataframe.
It is like a column or a row of a dataframe.

In [4]:
s=pd.Series([1,3,5,np.nan,6,8])
# note how nan is an element of numpy. 
print(s)
print(type(s))

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
<class 'pandas.core.series.Series'>


In [5]:
# Time series are very important for certain kind of data processing
# At least there is so much about time series everywhere.
# time series is for me at the moment not so important.
# I dont see any importance for "time evolution" in data (so far)


## Creating a time series

In [6]:
dates=pd.date_range('20130101',periods=6)
print(dates)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [7]:
df=pd.DataFrame(np.random.rand(6,4),index=dates,columns=list('ABCD'))
print(df)
# Note again how the dimensions have to fit.
# The dataframe is created passing the data of a two dimensional numpy array created ramdomly.
# Such array is 6x4, so 6 dates are neccesary as indexes and 4 column names.
# see how deleting on letter of the string ABCD would spit an error.

                   A         B         C         D
2013-01-01  0.032454  0.882226  0.446675  0.351854
2013-01-02  0.741414  0.901705  0.415631  0.003549
2013-01-03  0.179602  0.478852  0.568454  0.413010
2013-01-04  0.783716  0.234898  0.989542  0.640495
2013-01-05  0.836919  0.009969  0.692610  0.408315
2013-01-06  0.170976  0.776922  0.982307  0.884943


## Creating a dataframe passing a dicctionary

In [8]:
df2=pd.DataFrame({'A':1,
                  'B':pd.Timestamp('20130102'),
                 'C':pd.Series(1,index=list(range(4)),dtype='float32'),
                 'D':np.array([3]*4,dtype='int32'),
                'E': pd.Categorical(["test","train","test","train"]),
                'F': 'foo'})
print(df2)
# note how every column is of a different type.
# again dimensions have to fit. All series are of the same dimension.
# 'F' is a string, so it is get all the same along the column


   A          B    C  D      E    F
0  1 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  train  foo
2  1 2013-01-02  1.0  3   test  foo
3  1 2013-01-02  1.0  3  train  foo


## dataframe Methods
### dtypes, head(), tail(), index(), columns(), values()

In [9]:
print(df2.dtypes)

A             int64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [10]:
# first two lines
# note: using df, not df2
print(df.head(2))

                   A         B         C         D
2013-01-01  0.032454  0.882226  0.446675  0.351854
2013-01-02  0.741414  0.901705  0.415631  0.003549


In [11]:
# last three lines
print(df.tail(3))

                   A         B         C         D
2013-01-04  0.783716  0.234898  0.989542  0.640495
2013-01-05  0.836919  0.009969  0.692610  0.408315
2013-01-06  0.170976  0.776922  0.982307  0.884943


In [12]:
# the index and the columns
print(df.index)
print(df.columns)
# be aware that df.index ITS NOT A LIST, BUT AN OBJECT.
# THE LIST IS ACCESED AGAIN WITH .VALUES
print()
print('index values')
print(df.index.values)
print()
print('type of index:')
print(type(df.index))
print('type of index.values:')
print(type(df.index.values))


DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

index values
['2013-01-01T00:00:00.000000000' '2013-01-02T00:00:00.000000000'
 '2013-01-03T00:00:00.000000000' '2013-01-04T00:00:00.000000000'
 '2013-01-05T00:00:00.000000000' '2013-01-06T00:00:00.000000000']

type of index:
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
type of index.values:
<class 'numpy.ndarray'>


In [13]:
# it is possible to access JUST the values
print(df.values)
print()
print('the type variable of df.values is:')
print(type(df.values))
# the values are a two dimensional numpy array.
NP_values_Array=df.values
print()
print('np vlaues array size is:',NP_values_Array.size)
print('np vlaues array shape is:',NP_values_Array.shape)
print()

[[0.03245381 0.88222628 0.44667515 0.35185446]
 [0.741414   0.90170488 0.41563109 0.00354915]
 [0.17960189 0.47885186 0.56845389 0.41301016]
 [0.78371589 0.23489807 0.98954234 0.64049516]
 [0.83691853 0.00996885 0.69261005 0.40831515]
 [0.17097609 0.77692211 0.98230653 0.88494305]]

the type variable of df.values is:
<class 'numpy.ndarray'>

np vlaues array size is: 24
np vlaues array shape is: (6, 4)



In [14]:
## Operations with the values of a dataframe
### A dataframe can be operated as a matrix using his values (as seen above)

In [15]:
oNumPy=df.values
print(oNumPy)

[[0.03245381 0.88222628 0.44667515 0.35185446]
 [0.741414   0.90170488 0.41563109 0.00354915]
 [0.17960189 0.47885186 0.56845389 0.41301016]
 [0.78371589 0.23489807 0.98954234 0.64049516]
 [0.83691853 0.00996885 0.69261005 0.40831515]
 [0.17097609 0.77692211 0.98230653 0.88494305]]


In [16]:
# both are of the same type of data:
print(type(df.values))
print(type(oNumPy))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
# lets investigate how can we operate witht he values.
# multiplying vestors
# (m x n) x (n x k) = m x k
print(df.shape)

(6, 4)


In [18]:
# building a matrix (n x k) , lets say k=2
oa=np.array(([1,2,3,4],[5,6,7,8]))
print('oa shape')
print(oa.shape)
oa=oa.T
print('oa Transposed')
print(oa)
print()
print('df Transposed')
print(df.values.T)


oa shape
(2, 4)
oa Transposed
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

df Transposed
[[0.03245381 0.741414   0.17960189 0.78371589 0.83691853 0.17097609]
 [0.88222628 0.90170488 0.47885186 0.23489807 0.00996885 0.77692211]
 [0.44667515 0.41563109 0.56845389 0.98954234 0.69261005 0.98230653]
 [0.35185446 0.00354915 0.41301016 0.64049516 0.40831515 0.88494305]]


In [19]:
matrix1=df.values
matrix2=oa
print('{0} x {1}'.format(matrix1.shape,matrix2.shape))
print()
#print(matrix1.dtypes)
#print(matrix2.dtypes)
try:
    print(matrix1 * matrix2)
except:
    print('it does not work')
# TO DO: dot multiplication.
# print(dot(oNumPy*oa))

(6, 4) x (4, 2)

it does not work


# Sorting values
Sorting the columns (alphabetically)

In [20]:
print(df.sort_index(axis=1, ascending=False))
# in a dataframe axis=0 is rows
# axis=1 is columns

                   D         C         B         A
2013-01-01  0.351854  0.446675  0.882226  0.032454
2013-01-02  0.003549  0.415631  0.901705  0.741414
2013-01-03  0.413010  0.568454  0.478852  0.179602
2013-01-04  0.640495  0.989542  0.234898  0.783716
2013-01-05  0.408315  0.692610  0.009969  0.836919
2013-01-06  0.884943  0.982307  0.776922  0.170976


In [21]:
# ??? = why is it neccesary to specify axis=1 (0: index, 1:columns) if the function is called
# already sort_index
# works also for the columns?
print(df.sort_index(axis=0, ascending=False))
# yes it works also for columns, see how the columns are not listed in ascending order.

                   A         B         C         D
2013-01-06  0.170976  0.776922  0.982307  0.884943
2013-01-05  0.836919  0.009969  0.692610  0.408315
2013-01-04  0.783716  0.234898  0.989542  0.640495
2013-01-03  0.179602  0.478852  0.568454  0.413010
2013-01-02  0.741414  0.901705  0.415631  0.003549
2013-01-01  0.032454  0.882226  0.446675  0.351854


Sorting accrding to one Column

In [22]:
print(df.sort_values(by='B', ascending=False))

                   A         B         C         D
2013-01-02  0.741414  0.901705  0.415631  0.003549
2013-01-01  0.032454  0.882226  0.446675  0.351854
2013-01-06  0.170976  0.776922  0.982307  0.884943
2013-01-03  0.179602  0.478852  0.568454  0.413010
2013-01-04  0.783716  0.234898  0.989542  0.640495
2013-01-05  0.836919  0.009969  0.692610  0.408315


# Selection
Select a column

In [23]:
print(df['A'])
print()
print('when we select a column with this method we get:')
print(type(df['A']))

2013-01-01    0.032454
2013-01-02    0.741414
2013-01-03    0.179602
2013-01-04    0.783716
2013-01-05    0.836919
2013-01-06    0.170976
Freq: D, Name: A, dtype: float64

when we select a column with this method we get:
<class 'pandas.core.series.Series'>


In [24]:
print(df[0:3])
# curious to see that when specifying a number range 0 to 3 pandas interprets that 
# we are talking about indexes in rows.


                   A         B         C         D
2013-01-01  0.032454  0.882226  0.446675  0.351854
2013-01-02  0.741414  0.901705  0.415631  0.003549
2013-01-03  0.179602  0.478852  0.568454  0.413010


In [25]:
print(df['20130101':'20130102'])

                   A         B         C         D
2013-01-01  0.032454  0.882226  0.446675  0.351854
2013-01-02  0.741414  0.901705  0.415631  0.003549


In [26]:
# its strange that it is exactly the same layout for columns and for rows
# things that DO NOT work. 
# print(df.columns['A','B'])
# print(df['A','B'])
# curious enough df['A','B'] does not work but df['A'] works
try:
    print(df['A':'C'])
except:
    print("df['A':'C']", 'does not work')
    
try:
    print(df['A','C'])
except:
    print("df['A','C']", 'does not work')

try:
    print(df.columns['A':'C'])
except:
    print("df.columns['A':'C']", 'does not work')
    
    

df['A':'C'] does not work
df['A','C'] does not work
df.columns['A':'C'] does not work


In [27]:
# Alternative nomenclature
print(df.A)
print()
print(type(df.A))
print()
print('the values')
print(df.A.values)
print(type(df.A.values))

myArray=df.A.values
print(myArray[1])
print()
print('type of data myArray[1]')
print(type(myArray[1]))


2013-01-01    0.032454
2013-01-02    0.741414
2013-01-03    0.179602
2013-01-04    0.783716
2013-01-05    0.836919
2013-01-06    0.170976
Freq: D, Name: A, dtype: float64

<class 'pandas.core.series.Series'>

the values
[0.03245381 0.741414   0.17960189 0.78371589 0.83691853 0.17097609]
<class 'numpy.ndarray'>
0.7414139964920232

type of data myArray[1]
<class 'numpy.float64'>


## Without using loc iloc: 
What does work?
df['A','B'] NO
df['A':'B'] NO
df['A'] YES = the column A
df.A = YES equivalent to df['A'] 
df[0:3] YES = the Rows from 0 to 3
df['20130101':'20130102'] YES the rows from index first to index second
It looks like when putting into [] and between : the dataframe refers to rows.
With one only single value to a Column
The way not to get confused might be to use always df.A notation for columns since anyway it is not possible to access several columns with this notation & use the : separated values (integers or strings) to refer to rows.


# LOC
LOC= LOCATE. locate values based of
a combination of indexes entry (rows)
a combination of columns

In [28]:
# The index of the dataframe is a list "dates"
print(dates)


DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [29]:
print(dates[0])

2013-01-01 00:00:00


In [30]:
print(df.index[0])

2013-01-01 00:00:00


In [31]:
print(df.index[0]==dates[0])

True


In [32]:
print(df.loc[dates[0]])

A    0.032454
B    0.882226
C    0.446675
D    0.351854
Name: 2013-01-01 00:00:00, dtype: float64


Index and columns names are lists, therefore the values can be accessed as such: as unique values or as ranges separated by ':'
Slicing is King here. Like in any list.
It is possible to access single values or ranges, or lists of values.
The obvious way here to access ONE SINGLE POINT is refer to ONE ROW AND ONE COLUMN

In [33]:
# get the value corresponding the date 20130102 and column A
print(df.loc['20130102','A'])
print()
# Be aware!!!! with LOC you specify position with names.
# index name , column name

0.7414139964920232



In [34]:
print(df.loc['20130102':'20130104','A':'C'])

                   A         B         C
2013-01-02  0.741414  0.901705  0.415631
2013-01-03  0.179602  0.478852  0.568454
2013-01-04  0.783716  0.234898  0.989542


## Using ranges with LOC

In [35]:
print(df.loc['20130102':'20130104',['A','C']])
# this does not work:

                   A         C
2013-01-02  0.741414  0.415631
2013-01-03  0.179602  0.568454
2013-01-04  0.783716  0.989542


In [36]:
# I create a new dataframe having strings as indexes to avoid working with dates.
df3=pd.DataFrame(np.random.rand(6,4),index=['row1','row2','row3','row4','row5','row6'],columns=list('ABCD'))
print(df3)

             A         B         C         D
row1  0.890044  0.335384  0.329297  0.119863
row2  0.776955  0.366543  0.970135  0.258837
row3  0.714904  0.464015  0.524845  0.683201
row4  0.943850  0.593634  0.879107  0.640165
row5  0.460524  0.534652  0.169395  0.726782
row6  0.185527  0.539885  0.700319  0.167296


In [37]:
# now there are no dates in the index
print(df3.loc['row1':'row3', 'A':'C'])


             A         B         C
row1  0.890044  0.335384  0.329297
row2  0.776955  0.366543  0.970135
row3  0.714904  0.464015  0.524845


In [38]:
# accessing using a list of values.
print(df3.loc[['row1','row3'], 'A':'C'])

             A         B         C
row1  0.890044  0.335384  0.329297
row3  0.714904  0.464015  0.524845


In [39]:
print(df3.loc['row1':'row3', ['A','C']])

             A         C
row1  0.890044  0.329297
row2  0.776955  0.970135
row3  0.714904  0.524845


In [40]:
print(df3.loc['row1','A'])

0.890043987796399


# ILOC

Pandas provides a suite of methods in order to get purely integer based indexing. The semantics follow closely Python and NumPy slicing. These are 0-based indexing. When slicing, the start bounds is included, while the upper bound is excluded. Trying to use a non-integer, even a valid label will raise an IndexError.

The .iloc attribute is the primary access method. The following are valid inputs:

An integer e.g. 5.
A list or array of integers [4, 3, 0].
A slice object with ints 1:7.
A boolean array.
A callable, see Selection By Callable.

ILOC is therefore the I-NTEGER LOC-ATOR

In [41]:
# if we include only one index it refers to a ROW
print(df3.iloc[3])
print(df3.iloc[3].name)

A    0.943850
B    0.593634
C    0.879107
D    0.640165
Name: row4, dtype: float64
row4


In [42]:
# what about the index name of the series 3
print(df3.index[3])
print(type(df3.index[3]))

row4
<class 'str'>


In [43]:
# how to create a series to add to the pandas data frame.
# with append (which is very slow)
# df.append
# it is only possible to append a series, not a list.
a=12
b=34
c=45
d=56
# how to append those values.
mylist=[a,b,c,d]
print('we wan to append this list {0}'.format(mylist))

we wan to append this list [12, 34, 45, 56]


In [44]:
print(df3)

             A         B         C         D
row1  0.890044  0.335384  0.329297  0.119863
row2  0.776955  0.366543  0.970135  0.258837
row3  0.714904  0.464015  0.524845  0.683201
row4  0.943850  0.593634  0.879107  0.640165
row5  0.460524  0.534652  0.169395  0.726782
row6  0.185527  0.539885  0.700319  0.167296


In [45]:
# modify an entire row
df3.iloc[4]=[11111,22222,33333,44444]
print(df3)
print()
print('modify one value')
df3.iloc[5,1]='XXXXXX'
print(df3)
# Note that it is BASE 0!!!!!

                 A             B             C             D
row1      0.890044      0.335384      0.329297      0.119863
row2      0.776955      0.366543      0.970135      0.258837
row3      0.714904      0.464015      0.524845      0.683201
row4      0.943850      0.593634      0.879107      0.640165
row5  11111.000000  22222.000000  33333.000000  44444.000000
row6      0.185527      0.539885      0.700319      0.167296

modify one value
                 A         B             C             D
row1      0.890044  0.335384      0.329297      0.119863
row2      0.776955  0.366543      0.970135      0.258837
row3      0.714904  0.464015      0.524845      0.683201
row4      0.943850  0.593634      0.879107      0.640165
row5  11111.000000     22222  33333.000000  44444.000000
row6      0.185527    XXXXXX      0.700319      0.167296


In [46]:
# There are 6 rows. from 0 to 5
# what happends if I try to modify a index that does not exist
# case being inmediatly after the last one: row 7
try:
    df3.iloc[6,1]='NEW'
except:
    print('it does not work')

it does not work


In [47]:
# nevertheless with loc looks to work out
# There is no row called 'jose' but:
df3.loc['jose']=[7,8,9,0]
print(df3)
print()
# even adding a single value.
df3.loc['maria','C']='single value'
print(df3)
print()
print('pandas adds NaN to the values nokt specified.')

                 A         B             C             D
row1      0.890044  0.335384      0.329297      0.119863
row2      0.776955  0.366543      0.970135      0.258837
row3      0.714904  0.464015      0.524845      0.683201
row4      0.943850  0.593634      0.879107      0.640165
row5  11111.000000     22222  33333.000000  44444.000000
row6      0.185527    XXXXXX      0.700319      0.167296
jose      7.000000         8      9.000000      0.000000

                  A         B             C             D
row1       0.890044  0.335384      0.329297      0.119863
row2       0.776955  0.366543      0.970135      0.258837
row3       0.714904  0.464015      0.524845      0.683201
row4       0.943850  0.593634      0.879107      0.640165
row5   11111.000000     22222         33333  44444.000000
row6       0.185527    XXXXXX      0.700319      0.167296
jose       7.000000         8             9      0.000000
maria           NaN       NaN  single value           NaN

pandas adds NaN to t

In [48]:
# this is the advantage of having named indexes.
# you can always add in with a new index name.

In [49]:
# We have to convert the list into a pandas series.
# It is not possible to use append with a list
# -------- TO DO ---------------

## Adding rows 1

In [50]:
indexlist=['one']
columnList=list('ABC')
values=np.array([1,2,3])
# take care, the values array is a 3x1 size array. 
# rows has to be 1x3 so we have to reshape it
print('values size:',values.size)
values=values.reshape(1,3)
df4=pd.DataFrame(values,index=indexlist,columns=columnList)
print(df3)

values size: 3
                  A         B             C             D
row1       0.890044  0.335384      0.329297      0.119863
row2       0.776955  0.366543      0.970135      0.258837
row3       0.714904  0.464015      0.524845      0.683201
row4       0.943850  0.593634      0.879107      0.640165
row5   11111.000000     22222         33333  44444.000000
row6       0.185527    XXXXXX      0.700319      0.167296
jose       7.000000         8             9      0.000000
maria           NaN       NaN  single value           NaN


In [51]:
# what happend when adding "two" [5,6,7] and how to do it
# a) first create a series:
listtwo=[5,6,7]
oseries=pd.Series(listtwo)
print('type:',type(oseries))
print('values:',oseries.values)
print('name:',oseries.name)
oseries.name="two"
# I would like to add this series to the end of the dataframe


type: <class 'pandas.core.series.Series'>
values: [5 6 7]
name: None


In [52]:

# the following is equivalent, thats why the df printed is the same three times
df4.loc[oseries.name]=oseries.values
print(df4)
print()
# this does work:
df4.loc[oseries.name]=listtwo
print(df4)
print()
df4.loc['two']=[5,6,7]
print(df4)
print()
df4.append(oseries, ignore_index=True)
print(df4)


     A  B  C
one  1  2  3
two  5  6  7

     A  B  C
one  1  2  3
two  5  6  7

     A  B  C
one  1  2  3
two  5  6  7

     A  B  C
one  1  2  3
two  5  6  7


In [53]:
# what if I add a simple list
newlist=[8,9,0]
df4=df4.append(newlist)
print()
print(df4)


       A    B    C    0
one  1.0  2.0  3.0  NaN
two  5.0  6.0  7.0  NaN
0    NaN  NaN  NaN  8.0
1    NaN  NaN  NaN  9.0
2    NaN  NaN  NaN  0.0


## Add a dictionary

In [54]:
## from stack overflow
print('my dict',dict(zip(df4.columns, [4, 5, 6])))
print()
s = pd.Series(dict(zip(df4.columns, [4, 5, 6]))).rename('NEW')
print('myseries:')
print(s)
df4=df4.append(s)
print(df4)
print
print('see how the row name {0} is added'.format(s.name))
print('if you run this cell several times more rows named {0} are added'.format(s.name))
print('if you dont want that use LOC or ILOC')

my dict {'A': 4, 'B': 5, 'C': 6}

myseries:
A    4
B    5
C    6
Name: NEW, dtype: int64
       A    B    C    0
one  1.0  2.0  3.0  NaN
two  5.0  6.0  7.0  NaN
0    NaN  NaN  NaN  8.0
1    NaN  NaN  NaN  9.0
2    NaN  NaN  NaN  0.0
NEW  4.0  5.0  6.0  NaN
see how the row name NEW is added
if you run this cell several times more rows named NEW are added
if you dont want that use LOC or ILOC


/Users/jose/code/env/first/lib/python3.6/site-packages/ipykernel_launcher.py:7: RuntimeWarning: '<' not supported between instances of 'int' and 'str', sort order is undefined for incomparable objects
  import sys


In [55]:
# what if the dicctionary has one value not being a column name.
my_dict=dict(zip(df4.columns, [4, 5, 6]))
print('my dict',my_dict)
my_dict["H"]="YES NEW COLUMN H Added"
print('my dict modified:',my_dict)
print()
s = pd.Series(my_dict).rename('NEW2')
print('myseries:')
print(s)
df4=df4.append(s)
print(df4)
print
print('see how the row name {0} is added'.format(s.name))
print('if you run this cell several times more rows named {0} are added'.format(s.name))
print('if you dont want that use LOC or ILOC')

my dict {'A': 4, 'B': 5, 'C': 6}
my dict modified: {'A': 4, 'B': 5, 'C': 6, 'H': 'YES NEW COLUMN H Added'}

myseries:
A                         4
B                         5
C                         6
H    YES NEW COLUMN H Added
Name: NEW2, dtype: object
        A    B    C    0                       H
one   1.0  2.0  3.0  NaN                     NaN
two   5.0  6.0  7.0  NaN                     NaN
0     NaN  NaN  NaN  8.0                     NaN
1     NaN  NaN  NaN  9.0                     NaN
2     NaN  NaN  NaN  0.0                     NaN
NEW   4.0  5.0  6.0  NaN                     NaN
NEW2  4.0  5.0  6.0  NaN  YES NEW COLUMN H Added
see how the row name NEW2 is added
if you run this cell several times more rows named NEW2 are added
if you dont want that use LOC or ILOC


## Adding rows 2
df5

In [56]:
# take care, the values array is a 3x1 size array. 
# rows has to be 1x3 so we have to reshape it
df5=pd.DataFrame(np.array([1,2,3]).reshape(1,3),columns=list('ABC'))
print(df5)
# here the dataframe created does not have index

   A  B  C
0  1  2  3


In [57]:
# adding a simple list [5,6,7]
# NOT TO DO: PASSING LISTS TO APPEND LOC AND ILOC. NOOOO
# IN THE FUTURE WILL NOT WORK.
newlist=[5,6,7]

df6=df5.append(newlist)
print(df6)

     A    B    C    0
0  1.0  2.0  3.0  NaN
0  NaN  NaN  NaN  5.0
1  NaN  NaN  NaN  6.0
2  NaN  NaN  NaN  7.0


In [58]:
print('mydf5 before:')
print(df5)
my_dict=dict(zip(df.columns, [4, 5, 6]))
print()
print('mydict to add ',my_dict)
print()

s = pd.Series(my_dict)
print('myseries',print(s))
print()
print('adding series s')
print()

# series witout name, otherwise it would be:
# s = pd.Series(dict(zip(df.columns, [4, 5, 6])).rename('two'))
df5 = df5.append(s, ignore_index=True)
print('mydf5:')
print(df5)
print()


mydf5 before:
   A  B  C
0  1  2  3

mydict to add  {'A': 4, 'B': 5, 'C': 6}

A    4
B    5
C    6
dtype: int64
myseries None

adding series s

mydf5:
   A  B  C
0  1  2  3
1  4  5  6



In [59]:
hh='whatever'
my_dict2=dict(zip(df.columns, [hh,'sdfsdf','sdfsdf']))
s2=pd.Series(my_dict2)
df5 = df5.append(s2, ignore_index=True)
# If series does not have a name I have to forget ignore the index name.
print(df5)

s.name="Sname"
print(s.name)
# If we say ignore_index=False then the name of the series will be the index
df5 = df5.append(s, ignore_index=False)
print()
print('mydf5:')
print(df5)
print()

# this is the way to go if I just want to add stuff no matter the index.
# for instance when later on the dataframe is further processed (for duplicate values etc)

          A       B       C
0         1       2       3
1         4       5       6
2  whatever  sdfsdf  sdfsdf
Sname

mydf5:
              A       B       C
0             1       2       3
1             4       5       6
2      whatever  sdfsdf  sdfsdf
Sname         4       5       6



## reducing duplicates: agregating data with groupby dataframes

In [60]:
df6=pd.DataFrame(np.array(list('abcabfbhiblctzl')).reshape(5,3),columns=list('ABC'),index=list('JKLMN'))
print('before adding column D')
print(df6)
print()
df6['D']=[1,2,3,4,5]
print(df6)

before adding column D
   A  B  C
J  a  b  c
K  a  b  f
L  b  h  i
M  b  l  c
N  t  z  l

   A  B  C  D
J  a  b  c  1
K  a  b  f  2
L  b  h  i  3
M  b  l  c  4
N  t  z  l  5


In [61]:
# above it is possible to see that rows 0 and 1 have duplicates values
# how to get a row:
# a b c,f
df6= df6.groupby('A').agg({'B':'first', 
                             'C': ', '.join, 
                             }).reset_index()
# explanation: indicating the column where I want to add.
# indicate what to do with the other columns when adding.
# B: I take the first because they are the same. I could do any other operation
# Since I dont indicate anything about D it is not taking
print(df6)


   A  B     C
0  a  b  c, f
1  b  h  i, c
2  t  z     l


In [62]:
# lets assume I want to sum up the values of column D
df7=df6
df7['D']=[1,2,3]
df7= df7.groupby('A').agg({'B':'first', 
                             'C': ', '.join, 
                           'D': (lambda x : x.sum())
                             }).reset_index()
# mio: I guess when 'B' and 'D' ... are used it is taking as a list
print(df7)

   A  B     C  D
0  a  b  c, f  1
1  b  h  i, c  2
2  t  z     l  3


## real case

In [63]:
columnsList=['A','B','C','D']
df8=pd.DataFrame(columns=columnsList)
L=['value aa','value bb','value cc','value dd']
s = pd.Series(dict(zip(df8.columns, L)))
# remember to assign again df8, 
#the next line does not work:
df8.append(s,ignore_index=True)
df8=df8.append(s,ignore_index=True)
df8=df8.append(s,ignore_index=True)
# I EXPECT HERE A 2X4 DATAFRAME. 
print(df8.shape)
#>>> (0,4)
# adding a row at the end of the matrix
df8.loc[df8.index.max() + 1, :] = [4, 5, 6,7]
print(df8)

(2, 4)
          A         B         C         D
0  value aa  value bb  value cc  value dd
1  value aa  value bb  value cc  value dd
2         4         5         6         7


In [64]:
# when including ranges and list of values the situation is similar to LOC
# See my question in stack overflow about LOC

https://stackoverflow.com/questions/53903889/logic-behind-pandas-loc-selecting-values

In [65]:
print(df.iloc[3:5,0:2])

                   A         B
2013-01-04  0.783716  0.234898
2013-01-05  0.836919  0.009969


In [66]:
print(df.iloc[[3,5],0:2])

                   A         B
2013-01-04  0.783716  0.234898
2013-01-06  0.170976  0.776922


In [67]:
print(df.iloc[[3,5],[0,3]])

                   A         D
2013-01-04  0.783716  0.640495
2013-01-06  0.170976  0.884943


In [68]:
print(df.iloc[:,[0,3]])

                   A         D
2013-01-01  0.032454  0.351854
2013-01-02  0.741414  0.003549
2013-01-03  0.179602  0.413010
2013-01-04  0.783716  0.640495
2013-01-05  0.836919  0.408315
2013-01-06  0.170976  0.884943


In [69]:
print(df.iloc[4,1])

0.00996884553278976


In [70]:
import time
#I am going to count the running time of the program
start_time=time.time()
for i in range(100000):
    a=df.iloc[1,1]
elapsed_time=time.time()-start_time
print('time of iloc:',elapsed_time)
start_time=time.time()
for i in range(100000):
    a=df.iat[1,1]
elapsed_time=time.time()-start_time
print('time of iat',elapsed_time)




time of iloc: 2.514461040496826
time of iat 2.409627914428711


# number of elements

In [71]:
# number of rows of a dataframe
print('size of the dataframe is {0}'.format(df.shape))
print('the number of rows is {0}'.format(df.shape[0]))
print('the number of columns is {0}'.format(df.shape[1]))


size of the dataframe is (6, 4)
the number of rows is 6
the number of columns is 4


# selecting data conditionally

In [72]:
# Starting with a dataframe similar to reality.
indexlist=['concept1','concept2','concpet3','concept4','concept5']
# this is the list to be extended:
columnslist=['app','SUM']
print(columnslist)

# it is going to be extended with the values A and B
columnslist.extend(['A','B'])
print(columnslist)

# It is possible to make a list out of a string in this way
print(list('AB'))

# I realise that list['AB']= ['A','B']
#but this would not work:
try:
    columnslist.extend(list('AB'))
    print("it works: columnslist.extend(list('AB')) ")
    print(columnslist)
    
except:
    print("columnslist.extend(list['AB']) does not work")

# what about dividing a text into words
mytext="this is a text to be splitted"
oTextList=mytext.split()
print('this is the split text')
print(oTextList)
try:
    columnslist.extend(mytext.split())
    print(columnlist)
except:
    print("this does not work:")
    print("columnslist.extend(mytext.split())")


['app', 'SUM']
['app', 'SUM', 'A', 'B']
['A', 'B']
it works: columnslist.extend(list('AB')) 
['app', 'SUM', 'A', 'B', 'A', 'B']
this is the split text
['this', 'is', 'a', 'text', 'to', 'be', 'splitted']
this does not work:
columnslist.extend(mytext.split())


In [73]:
indexlist=[]
for i in range(20):
    indexlist.append('concept' + str(i))

indexlist.append('add')

columnslist=['app','SUM']
for i in range(7):
    columnslist.append('doc' + str(i))
    
rows = len(indexlist)
cols = len(columnslist)
a = np.matrix(np.random.randint(0,2, size=(rows, cols)))
matrixdf=pd.DataFrame(a,index=indexlist,columns=columnslist)
matrixdf.loc['add']= matrixdf.sum()
matrixdf.SUM=0
print(matrixdf) 

           app  SUM  doc0  doc1  doc2  doc3  doc4  doc5  doc6
concept0     1    0     0     1     1     0     1     1     0
concept1     0    0     0     0     0     0     0     1     0
concept2     0    0     1     0     1     0     1     1     1
concept3     0    0     1     0     0     0     1     0     1
concept4     1    0     1     1     1     1     0     0     0
concept5     1    0     0     0     0     0     0     1     1
concept6     1    0     0     1     0     1     0     0     1
concept7     1    0     1     0     1     1     0     0     1
concept8     1    0     0     0     0     1     1     0     1
concept9     1    0     0     0     0     1     1     0     1
concept10    1    0     1     0     1     0     0     0     1
concept11    0    0     1     1     1     1     0     0     1
concept12    1    0     1     1     1     1     0     0     0
concept13    0    0     0     1     0     1     0     1     1
concept14    0    0     0     1     0     1     0     0     0
concept1

In [74]:
# how to sum the other columns 
print(matrixdf.columns.values)
col_list= list(matrixdf.columns.values)
print(col_list)
print(type(col_list))
col_list.remove('app')
col_list.remove('SUM')
print(col_list)
matrixdf['SUM'] = matrixdf[col_list].sum(axis=1)
matrixdf.loc['add','app']=0
matrixdf.loc['add','SUM']=0
#matrixdf.app()
print(matrixdf)

['app' 'SUM' 'doc0' 'doc1' 'doc2' 'doc3' 'doc4' 'doc5' 'doc6']
['app', 'SUM', 'doc0', 'doc1', 'doc2', 'doc3', 'doc4', 'doc5', 'doc6']
<class 'list'>
['doc0', 'doc1', 'doc2', 'doc3', 'doc4', 'doc5', 'doc6']
           app  SUM  doc0  doc1  doc2  doc3  doc4  doc5  doc6
concept0     1    4     0     1     1     0     1     1     0
concept1     0    1     0     0     0     0     0     1     0
concept2     0    5     1     0     1     0     1     1     1
concept3     0    3     1     0     0     0     1     0     1
concept4     1    4     1     1     1     1     0     0     0
concept5     1    2     0     0     0     0     0     1     1
concept6     1    3     0     1     0     1     0     0     1
concept7     1    4     1     0     1     1     0     0     1
concept8     1    3     0     0     0     1     1     0     1
concept9     1    3     0     0     0     1     1     0     1
concept10    1    3     1     0     1     0     0     0     1
concept11    0    5     1     1     1     1     0 

In [75]:
# Filter out ot the matrix the subframe of the concepts of the application
# Using the filtering >0 in this way I can use RCS by Madou
ApplicationMatrix=matrixdf[matrixdf.app > 0]
ApplicationMatrix.loc['add']= ApplicationMatrix.sum()
print(ApplicationMatrix)

           app  SUM  doc0  doc1  doc2  doc3  doc4  doc5  doc6
concept0     1    4     0     1     1     0     1     1     0
concept4     1    4     1     1     1     1     0     0     0
concept5     1    2     0     0     0     0     0     1     1
concept6     1    3     0     1     0     1     0     0     1
concept7     1    4     1     0     1     1     0     0     1
concept8     1    3     0     0     0     1     1     0     1
concept9     1    3     0     0     0     1     1     0     1
concept10    1    3     1     0     1     0     0     0     1
concept12    1    4     1     1     1     1     0     0     0
concept15    1    3     1     0     1     0     0     0     1
concept16    1    5     0     1     1     0     1     1     1
concept18    1    4     1     1     0     1     0     1     0
add         12   42     6     6     7     7     4     4     8


/Users/jose/code/env/first/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [76]:
# Sort the columns of the matrix according to the last row
# the last row "add" is the number of concepts that appear in the document.
ApplicationMatrix = ApplicationMatrix.sort_values(ApplicationMatrix.last_valid_index(), axis=1, ascending=False)
print(ApplicationMatrix)

           SUM  app  doc6  doc2  doc3  doc0  doc1  doc4  doc5
concept0     4    1     0     1     0     0     1     1     1
concept4     4    1     0     1     1     1     1     0     0
concept5     2    1     1     0     0     0     0     0     1
concept6     3    1     1     0     1     0     1     0     0
concept7     4    1     1     1     1     1     0     0     0
concept8     3    1     1     0     1     0     0     1     0
concept9     3    1     1     0     1     0     0     1     0
concept10    3    1     1     1     0     1     0     0     0
concept12    4    1     0     1     1     1     1     0     0
concept15    3    1     1     1     0     1     0     0     0
concept16    5    1     1     1     0     0     1     1     1
concept18    4    1     0     0     1     1     1     0     1
add         42   12     8     7     7     6     6     4     4


In [77]:
# lets try to get the docs that have at least 80% of the concepts
# this value might be change by user
Similarity=80
#How many concepts are there?
nrConcepts=len(ApplicationMatrix.index)
nrDocs=round(80/100*len(ApplicationMatrix.index))
print(nrDocs)

10


# sorting the values of a dataframe sort

In [78]:
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'year': [2012, 2012, 2013, 2014, 2014], 
        'reports': [1, 2, 1, 2, 3],
        'coverage': [2, 2, 3, 3, 3]}
df = pd.DataFrame(data, index = ['Cochice', 'Pima', 'Santa Cruz', 'Maricopa', 'Yuma'])
print(df)

            coverage   name  reports  year
Cochice            2  Jason        1  2012
Pima               2  Molly        2  2012
Santa Cruz         3   Tina        1  2013
Maricopa           3   Jake        2  2014
Yuma               3    Amy        3  2014


In [80]:
# it is possible to sort on more than one column.
# first one column then the other one.
print(df.sort_values(by=['coverage', 'reports'], ascending=False))
# see how first the column coverage is ordered and then reports

            coverage   name  reports  year
Yuma               3    Amy        3  2014
Maricopa           3   Jake        2  2014
Santa Cruz         3   Tina        1  2013
Pima               2  Molly        2  2012
Cochice            2  Jason        1  2012


# A gentle introduction to Pandas (by medium.com)

https://medium.com/@harrypotter0/an-introduction-to-data-analysis-with-pandas-27ecbce2853